import type { Metadata } from "next";
// import { Inter } from "next/font/google";
import { Roboto } from "next/font/google";
import "./globals.css";

// const inter = Inter({ subsets: ["latin"] });
const robotoBold = Roboto({ 
  subsets: ['latin'],
  weight:  '700',
  display: 'swap',
  variable: '--font-roboto-bold',
 });
 const robotoReg = Roboto({ 
  subsets: ['latin'],
  weight:  '400',
  display: 'swap',
  variable: '--font-roboto-reg',
 });
 
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* <body className={inter.className}>{children}</body> */}
      <body>{children}</body>
    </html>
  );
}
